{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/SUMMER\\SQL2022;Contoso 5M",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "SUMMER\\SQL2022",
            "database": "Contoso 5M"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "summer\\sql2022;Contoso 5M",
          "Username": "antsharma",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Date",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Year Quarter",
            "dataType": "string",
            "sourceColumn": "Year Quarter"
          },
          {
            "name": "Year Quarter Number",
            "dataType": "int64",
            "sourceColumn": "Year Quarter Number"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Year Month",
            "dataType": "string",
            "sourceColumn": "Year Month"
          },
          {
            "name": "Year Month Short",
            "dataType": "string",
            "sourceColumn": "Year Month Short"
          },
          {
            "name": "Year Month Number",
            "dataType": "int64",
            "sourceColumn": "Year Month Number"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "Month Short",
            "dataType": "string",
            "sourceColumn": "Month Short"
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "Month Number"
          },
          {
            "name": "Day of Week",
            "dataType": "string",
            "sourceColumn": "Day of Week"
          },
          {
            "name": "Day of Week Short",
            "dataType": "string",
            "sourceColumn": "Day of Week Short"
          },
          {
            "name": "Day of Week Number",
            "dataType": "int64",
            "sourceColumn": "Day of Week Number"
          },
          {
            "name": "Working Day",
            "dataType": "boolean",
            "sourceColumn": "Working Day"
          },
          {
            "name": "Working Day Number",
            "dataType": "int64",
            "sourceColumn": "Working Day Number"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Database{[Name = \"Date\"]}[Data]",
                "in",
                "    Source"
              ]
            }
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "State Code",
            "dataType": "string",
            "sourceColumn": "State Code"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "Zip Code",
            "dataType": "string",
            "sourceColumn": "Zip Code"
          },
          {
            "name": "Country Code",
            "dataType": "string",
            "sourceColumn": "Country Code"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent"
          },
          {
            "name": "Birthday",
            "dataType": "dateTime",
            "sourceColumn": "Birthday"
          },
          {
            "name": "Age",
            "dataType": "int64",
            "sourceColumn": "Age"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Database{[Name = \"Customer\"]}[Data]",
                "in",
                "    Source"
              ]
            }
          }
        ]
      },
      {
        "name": "Product",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "sourceColumn": "Product Code"
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name"
          },
          {
            "name": "Manufacturer",
            "dataType": "string",
            "sourceColumn": "Manufacturer"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "Weight Unit Measure",
            "dataType": "string",
            "sourceColumn": "Weight Unit Measure"
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight"
          },
          {
            "name": "Unit Cost",
            "dataType": "decimal",
            "sourceColumn": "Unit Cost"
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price"
          },
          {
            "name": "Subcategory Code",
            "dataType": "string",
            "sourceColumn": "Subcategory Code"
          },
          {
            "name": "Subcategory",
            "dataType": "string",
            "sourceColumn": "Subcategory"
          },
          {
            "name": "Category Code",
            "dataType": "string",
            "sourceColumn": "Category Code"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Database{[Name = \"Product\"]}[Data]",
                "in",
                "    Source"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales",
        "columns": [
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "Order Date"
          },
          {
            "name": "Delivery Date",
            "dataType": "dateTime",
            "sourceColumn": "Delivery Date"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity"
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price"
          },
          {
            "name": "Net Price",
            "dataType": "decimal",
            "sourceColumn": "Net Price"
          },
          {
            "name": "Unit Cost",
            "dataType": "decimal",
            "sourceColumn": "Unit Cost"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Database{[Name = \"Sales\"]}[Data],",
                "    RemoveHighCardinalityColumns = Table.SelectColumns(Source,{\"Order Date\", \"Delivery Date\", \"CustomerKey\", \"StoreKey\", \"ProductKey\", \"Quantity\", \"Unit Price\", \"Net Price\", \"Unit Cost\"}),",
                "    LimitRows = if RowLimiter = -1 then RemoveHighCardinalityColumns else Table.FirstN ( RemoveHighCardinalityColumns, RowLimiter )",
                "in",
                "    LimitRows"
              ]
            }
          }
        ]
      },
      {
        "name": "Store",
        "columns": [
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey"
          },
          {
            "name": "Store Code",
            "dataType": "int64",
            "sourceColumn": "Store Code"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          },
          {
            "name": "Square Meters",
            "dataType": "int64",
            "sourceColumn": "Square Meters"
          },
          {
            "name": "Open Date",
            "dataType": "dateTime",
            "sourceColumn": "Open Date"
          },
          {
            "name": "Close Date",
            "dataType": "dateTime",
            "sourceColumn": "Close Date"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Database{[Name = \"Store\"]}[Data]",
                "in",
                "    Source"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "a86b9116-88a4-4247-b18a-17f7b5967ab8",
        "fromTable": "Sales",
        "fromColumn": "CustomerKey",
        "toTable": "Customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "f9da6d8f-127f-4fd8-9aa1-7a898c1d805f",
        "fromTable": "Sales",
        "fromColumn": "ProductKey",
        "toTable": "Product",
        "toColumn": "ProductKey"
      },
      {
        "name": "edace193-3d77-4918-97e2-f75faa3d0b75",
        "fromTable": "Sales",
        "fromColumn": "Order Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "462b760e-bd96-4aa8-ab22-14bbd679fe7a",
        "fromTable": "Sales",
        "fromColumn": "Delivery Date",
        "toTable": "Date",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "6c333e8b-7f0b-4100-8296-234a313bed03",
        "fromTable": "Sales",
        "fromColumn": "StoreKey",
        "toTable": "Store",
        "toColumn": "StoreKey"
      }
    ],
    "expressions": [
      {
        "name": "ServerName",
        "kind": "m",
        "expression": [
          "let",
          "    Source = \"SUMMER\\SQL2022\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
          "in",
          "    Source"
        ]
      },
      {
        "name": "DatabaseName",
        "kind": "m",
        "expression": [
          "let",
          "    Source = \"Contoso 5M\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
          "in",
          "    Source"
        ]
      },
      {
        "name": "RowLimiter",
        "kind": "m",
        "expression": [
          "let",
          "    Source = 100000 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
          "in",
          "    Source"
        ]
      },
      {
        "name": "Database",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Sql.Databases ( ServerName ){[Name = DatabaseName]}[Data],",
          "    KeepViews = Table.SelectRows ( Source, each [Kind] = \"View\" )",
          "in",
          "    KeepViews"
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}